[package]
name = "rsonnet"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.5.0"
miette = { version = "5.9.0", features = ["fancy"] }
peg = { version = "0.8.1", features = [] }
thiserror = "1.0.40"

[dev-dependencies]
assert_matches = "1.5.0"
