/* Generated by re2c 3.0 on Fri Jun 16 00:44:49 2023 */
#![allow(unused_braces, unused_mut, unused_variables, dead_code)]

use miette::SourceSpan;

use super::RawToken;

const COMMENT_START: &str = "/*";

#[rustfmt::skip]
pub(super) fn lexer(input: &str) -> (&str, SourceSpan, RawToken) {
    use RawToken::*;

    const NONE: usize = usize::MAX;

    let mut cursor: usize = 0;
    let mut marker: usize = 0;
    let mut ctxmarker: usize = 0;
    let mut yyt1 = 0;
    let mut yyt2 = 0;

    let mut s;

    let span = |s: usize, cursor: usize| SourceSpan::new(s.into(), (cursor - s).into());
    let debug = |state: usize, symbol: u8| {
        println!("lexer: state = {state}, symbol = '{}'", (symbol as char).escape_default());
    };

    let s = 'outer: loop {
        
        {
            #[allow(unused_assignments)]
            let mut yych : u8 = 0;
            let mut yyaccept : usize = 0;
            let mut yystate : usize = 0;
            'yyl: loop {
                match yystate {
                    0 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x09 ..= 0x0A |
                            0x0D |
                            0x20 => {
                                cursor += 1;
                                yystate = 3;
                                continue 'yyl;
                            }
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 5;
                                continue 'yyl;
                            }
                            0x22 => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 7;
                                continue 'yyl;
                            }
                            0x23 => {
                                cursor += 1;
                                yystate = 8;
                                continue 'yyl;
                            }
                            0x27 => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 9;
                                continue 'yyl;
                            }
                            0x28 ..= 0x29 |
                            0x2C |
                            0x2E |
                            0x3B |
                            0x5B |
                            0x5D |
                            0x7B |
                            0x7D => {
                                cursor += 1;
                                yystate = 10;
                                continue 'yyl;
                            }
                            0x2F => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 11;
                                continue 'yyl;
                            }
                            0x30 ..= 0x39 => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 12;
                                continue 'yyl;
                            }
                            0x40 => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 14;
                                continue 'yyl;
                            }
                            0x41 ..= 0x5A |
                            0x5F |
                            0x61 ..= 0x7A => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 15;
                                continue 'yyl;
                            }
                            0x7C => {
                                yyt1 = cursor;
                                cursor += 1;
                                yystate = 17;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 79;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 1;
                                continue 'yyl;
                            }
                        }
                    }
                    1 => {
                        yystate = 2;
                        continue 'yyl;
                    }
                    2 => { return (&input[cursor..], span(cursor, input.len()), Unknown(&input[cursor..])) }
                    3 => {
                        yystate = 4;
                        continue 'yyl;
                    }
                    4 => { continue 'outer }
                    5 => {
                        yyaccept = 0;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 5;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 18;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 19;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 6;
                                continue 'yyl;
                            }
                        }
                    }
                    6 => {
                        s = yyt1;
                        { break 'outer s }
                    }
                    7 => {
                        yyaccept = 1;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        if yych <= 0x00 {
                            if cursor >= input.len() {
                                yystate = 2;
                                continue 'yyl;
                            }
                            cursor += 1;
                            yystate = 20;
                            continue 'yyl;
                        }
                        yystate = 21;
                        continue 'yyl;
                    }
                    8 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x0A => {
                                yystate = 4;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 4;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 8;
                                continue 'yyl;
                            }
                        }
                    }
                    9 => {
                        yyaccept = 1;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        if yych <= 0x00 {
                            if cursor >= input.len() {
                                yystate = 2;
                                continue 'yyl;
                            }
                            cursor += 1;
                            yystate = 25;
                            continue 'yyl;
                        }
                        yystate = 26;
                        continue 'yyl;
                    }
                    10 => {
                        s = cursor;
                        s = (s as isize + -1) as usize;
                        { return (&input[cursor..], span(s, cursor), Symbol(&input[s..cursor])) }
                    }
                    11 => {
                        yyaccept = 1;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 30;
                                continue 'yyl;
                            }
                            0x2A => {
                                cursor += 1;
                                yystate = 31;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 8;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 32;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 2;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 28;
                                continue 'yyl;
                            }
                        }
                    }
                    12 => {
                        yyaccept = 2;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2E => {
                                cursor += 1;
                                yystate = 33;
                                continue 'yyl;
                            }
                            0x30 ..= 0x39 => {
                                cursor += 1;
                                yystate = 12;
                                continue 'yyl;
                            }
                            0x45 |
                            0x65 => {
                                cursor += 1;
                                yystate = 35;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 13;
                                continue 'yyl;
                            }
                        }
                    }
                    13 => {
                        s = yyt1;
                        { return (&input[cursor..], span(s, cursor), Number(&input[s..cursor])) }
                    }
                    14 => {
                        yyaccept = 1;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x22 => {
                                cursor += 1;
                                yystate = 36;
                                continue 'yyl;
                            }
                            0x27 => {
                                cursor += 1;
                                yystate = 37;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 2;
                                continue 'yyl;
                            }
                        }
                    }
                    15 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x30 ..= 0x39 |
                            0x41 ..= 0x5A |
                            0x5F |
                            0x61 ..= 0x7A => {
                                cursor += 1;
                                yystate = 15;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 16;
                                continue 'yyl;
                            }
                        }
                    }
                    16 => {
                        s = yyt1;
                        { return (&input[cursor..], span(s, cursor), Ident (&input[s..cursor])) }
                    }
                    17 => {
                        yyaccept = 1;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 40;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 41;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 42;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 2;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 38;
                                continue 'yyl;
                            }
                        }
                    }
                    18 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 30;
                                continue 'yyl;
                            }
                            0x2A => {
                                cursor += 1;
                                yystate = 43;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 44;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 32;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 28;
                                continue 'yyl;
                            }
                        }
                    }
                    19 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 40;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 41;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 45;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 38;
                                continue 'yyl;
                            }
                        }
                    }
                    20 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        yystate = 21;
                        continue 'yyl;
                    }
                    21 => {
                        match yych {
                            0x22 => {
                                cursor += 1;
                                yystate = 22;
                                continue 'yyl;
                            }
                            0x5C => {
                                cursor += 1;
                                yystate = 24;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 20;
                                continue 'yyl;
                            }
                        }
                    }
                    22 => {
                        yystate = 23;
                        continue 'yyl;
                    }
                    23 => {
                        s = yyt1;
                        { return (&input[cursor..], span(s, cursor), String(&input[s..cursor])) }
                    }
                    24 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x22 => {
                                cursor += 1;
                                yystate = 46;
                                continue 'yyl;
                            }
                            0x5C => {
                                cursor += 1;
                                yystate = 24;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 20;
                                continue 'yyl;
                            }
                        }
                    }
                    25 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        yystate = 26;
                        continue 'yyl;
                    }
                    26 => {
                        match yych {
                            0x27 => {
                                cursor += 1;
                                yystate = 22;
                                continue 'yyl;
                            }
                            0x5C => {
                                cursor += 1;
                                yystate = 27;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 25;
                                continue 'yyl;
                            }
                        }
                    }
                    27 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x27 => {
                                cursor += 1;
                                yystate = 47;
                                continue 'yyl;
                            }
                            0x5C => {
                                cursor += 1;
                                yystate = 27;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 25;
                                continue 'yyl;
                            }
                        }
                    }
                    28 => {
                        yystate = 29;
                        continue 'yyl;
                    }
                    29 => {
                        s = yyt1;
                        cursor = (cursor as isize + -1) as usize;
                        { break 'outer s }
                    }
                    30 => {
                        yyaccept = 0;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 48;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 49;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 6;
                                continue 'yyl;
                            }
                        }
                    }
                    31 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2A => {
                                cursor += 1;
                                yystate = 50;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 31;
                                continue 'yyl;
                            }
                        }
                    }
                    32 => {
                        yyaccept = 3;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 51;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 52;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 53;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 29;
                                continue 'yyl;
                            }
                        }
                    }
                    33 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x30 ..= 0x39 => {
                                cursor += 1;
                                yystate = 54;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    34 => {
                        cursor = marker;
                        match yyaccept {
                            0 => {
                                yystate = 6;
                                continue 'yyl;
                            }
                            1 => {
                                yystate = 2;
                                continue 'yyl;
                            }
                            2 => {
                                yystate = 13;
                                continue 'yyl;
                            }
                            3 => {
                                yystate = 29;
                                continue 'yyl;
                            }
                            4 => {
                                yystate = 39;
                                continue 'yyl;
                            }
                            5 => {
                                yystate = 23;
                                continue 'yyl;
                            }
                            6 => {
                                yystate = 58;
                                continue 'yyl;
                            }
                            7 => {
                                yystate = 4;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 78;
                                continue 'yyl;
                            }
                        }
                    }
                    35 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2B |
                            0x2D => {
                                cursor += 1;
                                yystate = 55;
                                continue 'yyl;
                            }
                            0x30 ..= 0x39 => {
                                cursor += 1;
                                yystate = 56;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    36 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x22 => {
                                cursor += 1;
                                yystate = 57;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 36;
                                continue 'yyl;
                            }
                        }
                    }
                    37 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x27 => {
                                cursor += 1;
                                yystate = 60;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 59;
                                continue 'yyl;
                            }
                        }
                    }
                    38 => {
                        yystate = 39;
                        continue 'yyl;
                    }
                    39 => {
                        s = yyt1;
                        cursor = (cursor as isize + -1) as usize;
                        { break 'outer s }
                    }
                    40 => {
                        yyaccept = 0;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 61;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 62;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 6;
                                continue 'yyl;
                            }
                        }
                    }
                    41 => {
                        yyaccept = 4;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 63;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 64;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 39;
                                continue 'yyl;
                            }
                        }
                    }
                    42 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 40;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 41;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 65;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 38;
                                continue 'yyl;
                            }
                        }
                    }
                    43 => {
                        s = yyt1;
                        cursor = (cursor as isize + -2) as usize;
                        { break 'outer s }
                    }
                    44 => {
                        s = yyt1;
                        cursor = (cursor as isize + -2) as usize;
                        { break 'outer s }
                    }
                    45 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 40;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 41;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 66;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 38;
                                continue 'yyl;
                            }
                        }
                    }
                    46 => {
                        yyaccept = 5;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x22 => {
                                cursor += 1;
                                yystate = 22;
                                continue 'yyl;
                            }
                            0x5C => {
                                cursor += 1;
                                yystate = 24;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 23;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 20;
                                continue 'yyl;
                            }
                        }
                    }
                    47 => {
                        yyaccept = 5;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x27 => {
                                cursor += 1;
                                yystate = 22;
                                continue 'yyl;
                            }
                            0x5C => {
                                cursor += 1;
                                yystate = 27;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 23;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 25;
                                continue 'yyl;
                            }
                        }
                    }
                    48 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 48;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 49;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    49 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 30;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    50 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2A => {
                                cursor += 1;
                                yystate = 50;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 67;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 31;
                                continue 'yyl;
                            }
                        }
                    }
                    51 => {
                        yyaccept = 0;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 68;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 52;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 6;
                                continue 'yyl;
                            }
                        }
                    }
                    52 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x7C => {
                                cursor += 1;
                                yystate = 69;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    53 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 51;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 52;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    54 => {
                        yyaccept = 2;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x30 ..= 0x39 => {
                                cursor += 1;
                                yystate = 54;
                                continue 'yyl;
                            }
                            0x45 |
                            0x65 => {
                                cursor += 1;
                                yystate = 35;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 13;
                                continue 'yyl;
                            }
                        }
                    }
                    55 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x30 ..= 0x39 => {
                                cursor += 1;
                                yystate = 56;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    56 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x30 ..= 0x39 => {
                                cursor += 1;
                                yystate = 56;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 13;
                                continue 'yyl;
                            }
                        }
                    }
                    57 => {
                        yyaccept = 6;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x22 => {
                                cursor += 1;
                                yystate = 36;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 58;
                                continue 'yyl;
                            }
                        }
                    }
                    58 => {
                        s = yyt1;
                        { return (&input[cursor..], span(s, cursor), StringVerbatim(&input[s..cursor])) }
                    }
                    59 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x27 => {
                                cursor += 1;
                                yystate = 70;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    60 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x27 => {
                                cursor += 1;
                                yystate = 59;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    61 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 61;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 62;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    62 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 40;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 71;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    63 => {
                        yyaccept = 0;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 72;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 64;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 6;
                                continue 'yyl;
                            }
                        }
                    }
                    64 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2F => {
                                cursor += 1;
                                yystate = 73;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 74;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    65 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x7C => {
                                cursor += 1;
                                yystate = 75;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 65;
                                continue 'yyl;
                            }
                        }
                    }
                    66 => {
                        s = yyt1;
                        cursor = (cursor as isize + -3) as usize;
                        { break 'outer s }
                    }
                    67 => {
                        yyaccept = 7;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2A => {
                                cursor += 1;
                                yystate = 50;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 4;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 31;
                                continue 'yyl;
                            }
                        }
                    }
                    68 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 68;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 52;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    69 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 51;
                                continue 'yyl;
                            }
                            0x2F => {
                                cursor += 1;
                                yystate = 52;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 53;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    70 => {
                        yystate = 58;
                        continue 'yyl;
                    }
                    71 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 40;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    72 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2A ..= 0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 72;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 64;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    73 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x21 |
                            0x24 ..= 0x26 |
                            0x2B |
                            0x2D |
                            0x3A |
                            0x3C ..= 0x3E |
                            0x5E |
                            0x7E => {
                                cursor += 1;
                                yystate = 63;
                                continue 'yyl;
                            }
                            0x7C => {
                                cursor += 1;
                                yystate = 64;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    74 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x2F => {
                                cursor += 1;
                                yystate = 73;
                                continue 'yyl;
                            }
                            _ => {
                                yystate = 34;
                                continue 'yyl;
                            }
                        }
                    }
                    75 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x7C => {
                                cursor += 1;
                                yystate = 76;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 65;
                                continue 'yyl;
                            }
                        }
                    }
                    76 => {
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x7C => {
                                cursor += 1;
                                yystate = 77;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 34;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 65;
                                continue 'yyl;
                            }
                        }
                    }
                    77 => {
                        yyaccept = 8;
                        marker = cursor;
                        yych = input.as_bytes().get(cursor).copied().unwrap_or(0);
                        match yych {
                            0x7C => {
                                cursor += 1;
                                yystate = 77;
                                continue 'yyl;
                            }
                            _ => {
                                if cursor >= input.len() {
                                    yystate = 78;
                                    continue 'yyl;
                                }
                                cursor += 1;
                                yystate = 65;
                                continue 'yyl;
                            }
                        }
                    }
                    78 => {
                        s = yyt1;
                        { return (&input[cursor..], span(s, cursor), StringBlock(&input[s..cursor])) }
                    }
                    79 => { return (&input[cursor..], span(cursor, cursor), Eof) }
                    _ => {
                        panic!("internal lexer error")
                    }
                }
            }
        }

    };

    let mut op = &input[s..cursor];
    op = match op.trim_end_matches(['+', '-', '~', '!', '$']) {
        "" => &op[..1],
        trimmed => trimmed,
    };

    return (&input[s + op.len()..], span(s, s + op.len()), Operator(op))
}
